name: ${project.artifactId}
version: ${project.version}
api-version: 1.21
main: org.ferrum.debugStick.DebugStick
folia-supported: true
load: STARTUP
authors: [ Egor_ ]

commands:
  debugstick:
    description: reload config
    usage: use /debugstick reload

permissions:
  debugstick.bypass:
    default: false
    description: Bypassing plugin check
  debugstick.reload:
    default: op
    description: Permission to reload the plugin
